# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PickupLocation.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox,QTableWidget,QTableWidget
from PyQt5.QtSql import QSqlDatabase, QSqlTableModel
from PyQt5.QtWidgets import *
from PyQt5.QtGui  import *
from PyQt5.QtCore import *

pickupBuilding = ""
confPBuilding = False

class Ui_PLWindow(object):

    def setupUi(self, Ui_PLWindow):
        Ui_PLWindow.setObjectName("Ui_PLWindow")
        Ui_PLWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(Ui_PLWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pickLoc1 = QtWidgets.QPushButton(self.centralwidget)
        self.pickLoc1.setGeometry(QtCore.QRect(260, 110, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pickLoc1.setFont(font)
        self.pickLoc1.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pickLoc1.setObjectName("pickLoc1")
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(160, 40, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("")
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.pickLoc2 = QtWidgets.QPushButton(self.centralwidget)
        self.pickLoc2.setGeometry(QtCore.QRect(260, 190, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pickLoc2.setFont(font)
        self.pickLoc2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pickLoc2.setObjectName("pickLoc2")
        self.pickLoc3 = QtWidgets.QPushButton(self.centralwidget)
        self.pickLoc3.setGeometry(QtCore.QRect(260, 270, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pickLoc3.setFont(font)
        self.pickLoc3.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pickLoc3.setObjectName("pickLoc3")
        self.PLLabel = QtWidgets.QLabel(self.centralwidget)
        self.PLLabel.setGeometry(QtCore.QRect(150, 360, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PLLabel.setFont(font)
        self.PLLabel.setStyleSheet("")
        self.PLLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PLLabel.setObjectName("PLLabel")  
        self.confirmBtn = QtWidgets.QPushButton(self.centralwidget) 
        self.confirmBtn.setGeometry(QtCore.QRect(190, 420, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.confirmBtn.setFont(font)
        self.confirmBtn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.confirmBtn.setObjectName("confirmBtn")
        Ui_PLWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_PLWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        self.menubar.setObjectName("menubar")
        Ui_PLWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_PLWindow)
        self.statusbar.setObjectName("statusbar")
        Ui_PLWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_PLWindow)
        QtCore.QMetaObject.connectSlotsByName(Ui_PLWindow)

    # Button triggers here
        
        self.pickLoc1.clicked.connect(lambda: self.clicked("Building 1"))
        self.pickLoc2.clicked.connect(lambda: self.clicked("Building 2"))
        self.pickLoc3.clicked.connect(lambda: self.clicked("Building 3"))

        self.confirmBtn.clicked.connect(lambda: self.clicked("Confirm"))
    # end button triggers

    def retranslateUi(self, Ui_PLWindow):
        _translate = QtCore.QCoreApplication.translate
        Ui_PLWindow.setWindowTitle(_translate("Ui_PLWindow", "Ui_PLWindow"))
        self.pickLoc1.setText(_translate("Ui_PLWindow", "Building 1"))
        self.statusLabel.setText(_translate("Ui_PLWindow", "Please select a Pickup Location"))
        self.pickLoc2.setText(_translate("Ui_PLWindow", "Building 2"))
        self.pickLoc3.setText(_translate("Ui_PLWindow", "Building 3"))
        self.confirmBtn.setText(_translate("Ui_PLWindow", "Confirm Pickup Location"))
        self.PLLabel.setText(_translate("Ui_PLWindow", "Current Pickup Location: "))

    def clicked(self, text):
        global pickupBuilding

        confPBuilding = False

        if text == "Building 1":
            print("Building 1 selected")
            pickupBuilding = text
        if text == "Building 2":
            print("Building 2 selected")
            pickupBuilding = text
        if text == "Building 3":
            print("Building 3 selected")
            pickupBuilding = text
        if text == "Confirm":
            print("Confirmed pickup")
            self.PLLabel.setText("Will pick up merchandise at " + pickupBuilding)
            self.PLLabel.adjustSize()
            self.PLLabel.setAlignment(Qt.AlignCenter)
            self.insertPL(pickupBuilding)
            confPBuilding = True

        if confPBuilding == False:
            self.PLLabel.setText("Current Pickup Location: " + pickupBuilding)
            self.PLLabel.adjustSize()

    def insertPL(self,l):
        curRow = self.whichRow()
        
        PLcon = sqlite3.connect("Z:\BPT.db")

        print("connected for insert PL\n")

        cursor = PLcon.cursor()

        insLoc = "UPDATE tasks SET Pickup_Location ='"+l+"' WHERE row_ID = "+curRow+";"

        cursor.execute(insLoc)
        PLcon.commit()
        PLcon.close()

    def whichRow(self):
        con = sqlite3.connect("Z:\BPT.db")
        cellCon = con.cursor()

        cellCon.execute('SELECT Current_Row FROM states')
        data = cellCon.fetchone()
        rw = str(data[0])
        print("Current_Row is:" + str(rw))
        return rw

    def startUp():
        global PLWindow
        app = QtWidgets.QApplication(sys.argv)
        PLWindow = QtWidgets.QMainWindow()
        ui = Ui_PLWindow()
        ui.setupUi(PLWindow)
        PLWindow.show()
        sys.exit(app.exec_())

class SQL_Table(QMainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Delivery Request Window")
        self.resize(1200, 200)
        # Set up the model
        self.model = QSqlTableModel(self)
        self.model.setTable("tasks")
        self.model.setEditStrategy(QSqlTableModel.OnFieldChange)
        self.model.setHeaderData(0, Qt.Horizontal, "Work_Order")
        self.model.setHeaderData(1, Qt.Horizontal, "QTY")
        self.model.setHeaderData(2, Qt.Horizontal, "Pickup_Location")
        self.model.setHeaderData(3, Qt.Horizontal, "Delivery_Location")
        self.model.select()
        # Set up the view
        self.view = QTableView()
        self.view.setModel(self.model)
        self.view.resizeColumnsToContents()
        self.setCentralWidget(self.view)

    # Creates the GUI's connection to the SQLite database on the Raspberry Pi
    def createConnection():
        con = QSqlDatabase.addDatabase("QSQLITE")
        # Sets the file path of the SQL Database file
        # **Note**: Change this to the path of your SQL database located on your local network drive
        con.setDatabaseName("Z:\BPT.db")
        if not con.open():
            # Returns the following message if program fails to connect to database
            QMessageBox.critical(
                None,
                "QTableView Example - Error!",
                "Database Error: %s" % con.lastError().databaseText(),
            )
            return False
        return True

if __name__ == "__main__":
   Ui_PLWindow.startUp()

if not SQL_Table.createConnection():
    sys.exit(1)
DB_win = SQL_Table()
